name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --u "${DOCKER_USERNAME}" --password-stdin
          
          echo "Building and pushing Docker image..."
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --file ./Dockerfile --output type=image,push=true --tag "job-portal:latest" .



