name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: voetaz123
        password: Rizaldy123*

    - name: Build and Push Docker Image
      run: |
        docker-compose build
        docker-compose push

    - name: SSH into Server
      uses: appleboy/ssh-action@master
      with:
        host: 139.59.118.164
        username: zaldee
        key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCfwXOqpfD53hKWrPZJSXc/AAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDO1BDH7hfx7kBp+JE0Xm1yt78xyn27DbjTsMA1ndBMRbhRxrp2cpKyx70IEs9BdVu6ZLfSz3g/oxi2EnpIJV49PkCdG/jdIbRX3TsS7Yfr0umPaENHGwm9UL7x+xB6CDh103QXUpHJx9RgdiQGTB0669Tim0oMcHQ8qObG19b3GxRDyy7b52k/7e1IcEAK/YLKjjqd+idydDgBD8y6m352kYHDMhr85OjnSLc/hsflR/ZvoyHDoGsWHuw/uACH2x966zMQ0IC2z2PsdRpUXBaHpLbulenSfgqboCDxLi48dVoY8jY1VF3UCcflzWZZDNk2PpbeWrMrRW9zio6vrmi4rKrpV0UCOVrE91avHnHS8o9yrpqZIn1WRmuATw37QriSlybkT+LL3SJ6YzfYMpFwqprlMW5tkhZQcxTw4h0x5AMZcwsmvmH0GmtlQNX3B7f8P0uidFtgGj3KuCQc3IIPO8MfXcCbgTXOBhPFFdTNFzNs9fVWYE7PVuahyrdw9M8AAAWgAjtYRDflsQvSNYACshVcvBy7fiLPri2TQzBs7BQ5Fp/82y4LdAX+NEie6k1PNlzuAR/ObuttXTxQgALTuaTyzgLZPzoUViWxftxkulUwVbfoWLJsdVKtBkenGnbgc3Ae2Hedvj/efXD0wB7tvZLdb30OY2BfQCTu8AvA9uQoiaBskj4Yo+woSrgLQ40Iq3QBapQGZ0jTpkvbo8+XXTYq1sNDlIHhbIoTSv6S6GSjGiEnWXUSUmTCNCB4jBBt0lbeavMdup3tPXsQam/RiuIQOa/r/U2xVL3rOPlMc2vnbIYojGnSvYcGlqPHQ2WTKvuOBqOM3+Pdbyt1CuQXKpk1Kn8RzJYDHro8mFZ2WakIie5PujrizsU+vOaEqcHZ0V1zEgjfO52lLsxqOsGbwLdiCSzGHfB8ICQgKLrsrGffYJEjBEsOe4oidxvB6DpxV9+J9NcooczxU3jhp+9+6hZBP96IdS6yVQh/mDKA3xCQdC/xVCUXGLORWNEEFZnV8AvXvviGT7BhrHXHknxG9c6XZe+XyE+x7SbxUWOgmIQaz7PF0fN+KSLSObenDLehO8Yb5UwBd0OwbDoZImEc8thsczGmbS2vlmJMZAUEj/WEB8mb3/JSG/etN+LJMpfE3kI9hbsxsEh5ygP33c7FiIp6G1DwcZWOD1oNHVGIJiCIUDlEBmpJE0Ks2FUHb7Kx8qNKeNVYB4pAVqF5UTqVahyHyQyA+cmna057bzXG1hmw53p2H+j2CAuexP9Mq3pDq4OrFgT4I1BsCaxJUCgqBhzKvP5Qaanl3CuZpxPVh1C2cE/i5DnX4gvljLjzqJ5MQJtaOzMQ9GH7JfwZ6mwapGd8tMWS8vyE2TXS/WRsXhcy9tcmXTXhuEpYmpRvqyeJNDf5/yDwUBi8oDxcnN7U//7uUd/pESfAdVkpjP652A2lROh2gBhbCaq94+9g9yBhpLo6oRCb/wcxc+th8qqGAK7A7XluPrM2+hNRo5QyD9WCiTYFvA6cNUPSw8Jm7Yu73YMJMD1lb/tZJd7KI1vo0iFGoJmmgLFLwYhKM9Jb8JwcflgoFuEw42FMLiSY5y632Qqs/5MMRDeXfvMEyrOnqAsCoY2ceiNVtdScz41ZKK+52TBrOFO243LBjKPFOE87Ez2iqN+/Bwv0vhzJ7fMl8jJ9Wxej/xgE+GMqIT36lYalgIzSd7QkbmgiGGNJhf739fwue/oJz3rzgwYNmZXP3VFYPwBkQ3cQaLAxIz/n0d+ak9Xi0SFAypseLtFRihCi7E9SXZSmSBXijSUq1WCsVNjG6cYy+x9nsN11amDIcouzNckJzlYlIMv31aabfEcyswmKDz4nxj6gZBmeKiY13WkhcfnB1ZhWx7O1vCuwirGV1uJLsxxh4lXs68kAgYwCKcBllzgO/y/28J+poq6/mnyqCrpbbiVBy5i9NVAHm3tTlRP3TRzdaGQACFHeRrtwjpAO9jL+y4z9JFh7MBd/8IySHo7O5ls1DGe5bAhx2as4Ia4e8bbAWrVG4tquIrDookBEumKmjz1rIaS1XMD/zrO8t+Aj9FOPsNnMdtfdNeekQ0V8Fj97OKmHObcrAg9yXCfMz2pT9Lclguo338uND9QE46ZeLARy9m6Kp/h17dVljHnkJTMeVPXU8iKgQVBrrxit55zhLq9fRKPxUZUhPt3vd5GGfu9f+qdkA8WOYer+Vt/NzDfYOmoVy6nlCnkoSDsKik9GBFl7835wrlu/ENUpYXXWP1/AMK1CDqrMnzoakdL1d3Ls327VPJpDI0IDz1tt/ovBQ612uduUc/akLbD+bARN+Kb2ysTcy9S2D77kO7QNAS43h4/pn8uKoyg2eYesq7DaG/lQBlJiD+PzleeZ3NaTzY4aqvKD8KliThpewHalOY3cOFl1JNt+3qsxPe+6
        passphrase: Voetaz123*
        script: |
          cd /app
          docker-compose pull
          docker-compose up -d
