name: Build Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
          registry-url: "https://registry.yarnpkg.com"

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js App
        run: yarn build

      - name: Run App
        run: yarn start
